apiVersion: v1
kind: Secret
type: cos-s3-csi-driver
metadata:
  name: {{ .SecretName }}
  namespace: {{ .Namespace }}
stringData:
  accessKey: "{{ .AccessKey }}"
  secretKey: "{{ .SecretKey }}"
  bucketName: "{{ .BucketName }}"
  endpoint: "{{ .Endpoint }}"
  serviceInstanceID: "{{ .ServiceInstanceID }}"
  bucketVersioning: "false"
  mountOptions: |
    max_stat_cache_size={{ .StatCacheSize }}
    parallel_count={{ .ParallelCount }}
    multipart_size={{ .ChunkSizeMB }}
    multireq_max={{ .MultireqMax }}
    {{ .KernelCache }}
    retries={{ .Retries }}
    allow_other
    max_dirty_data=5120